force-app/main/default/objects/Location/fields/WarehouseID__c.field-meta.xml
<CustomField>
    <fullName>WarehouseID__c</fullName>
    <label>WarehouseID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MSN_LN_Material_Key__c.field-meta.xml
<CustomField>
    <fullName>MSN_LN_Material_Key__c</fullName>
    <description>The unique identifier of the Product/Part in the external Watercare system &quot;LN&quot;</description>
    <externalId>true</externalId>
    <label>LN Material Key</label>
    <length>6</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductItem/fields/MSN_LN_Material_Key__c.field-meta.xml
<CustomField>
    <fullName>MSN_LN_Material_Key__c</fullName>
    <description>This cross-object formula field is used to retrieve the unique &quot;LN Material Key&quot; from the Product and populate the field on the Product Item. This is then used e.g. by the field crew on their Field Service Mobile App to consume Products by scanning a printed Barcode (= LN Material Key) of the Product instead of having to search for it manually in the app.</description>
    <formula>Product2.MSN_LN_Material_Key__c</formula>
    <label>LN Material Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MSN_RestResourceLNPartSync_Test.cls
/**
 * @File Name          : MSN_RestResourceLNPartSync_Test.cls
 * @Description        : Test class for MSN_RestResourceLNPartSync.cls
 * @Author             : Ashwini Patil
 * @Last Modified By   : 
 * @Last Modified On   : 
 * @Modification Log   : 
 * 1. improve testing scenario
 * 2. improve test coverage
 * 3. correct bugs
 * Ver      Date            Author                  Modification
 * 1.0      22/08/2022      Ashwini Patil           Initial Version
 * 2.0      18/01/2023      Bohao Chen           Updated version
**/

@isTest
public class MSN_RestResourceLNPartSync_Test {

  @TestSetup
    static void insertrecord(){
        //Schema.Location loc = (Schema.Location)TestDataFactory.createSObject('Schema.Location');
        Schema.Location lo = new Schema.Location(Name = 'Test', LocationType = 'Van', WarehouseID__c  = 'OF0001', IsInventoryLocation = true );  
        insert lo;       


        Product2 product = (Product2)TestDataFactory.createSObject('Product2', new Map<String,Object>{
            'MSN_LN_Material_Key__c' => '100069'
        });

        ProductItem pi = (ProductItem)TestDataFactory.createSObject('ProductItem', new Map<String,Object>{
            'LocationId' => lo.Id,
            'Product2Id ' => product.Id
        });      
    }
    
    
    static testMethod void positiveTest() {
        System.RestRequest req = new System.RestRequest(); 
        System.RestResponse res = new System.RestResponse();

        MSN_LNPayloadData payloadrequest = new MSN_LNPayloadData();
        payloadrequest.TransactionID = '7936';
        payloadrequest.ItemID = '100069';
        payloadrequest.WarehouseID = 'OF0001';
        payloadrequest.WarehouseName = 'Test';
        payloadrequest.UnitCode = 'EA';
        payloadrequest.Quantity = 9;
        payloadrequest.Success = 'true';
        
        req.requestURI = '/services/apexrest/LNPartSync/';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(JSON.serializePretty(payloadrequest));
        
        RestContext.request = req;
        RestContext.response = res;
     
        Test.startTest();

        MSN_RestResourceLNPartSync.updatepartquantity();

        System.assertEquals(200, res.statusCode);
        RestResponse resp = (RestResponse)JSON.deserialize(res.responseBody.toString(), RestResponse.class);
        
        System.assertEquals(MSN_RestResourceLNPartSync.SUCCESS_MSG, resp.Description);
        System.debug('res : ' + res);
        Test.stopTest();                                                                 
    }
  
     static testMethod void negativeTest() {
        System.RestRequest req = new System.RestRequest(); 
        System.RestResponse res = new System.RestResponse();

        MSN_LNPayloadData payloadrequest = new MSN_LNPayloadData();
        payloadrequest.TransactionID = '7936';
        payloadrequest.ItemID = '100068';
        payloadrequest.WarehouseID = 'OF0001';
        payloadrequest.WarehouseName = 'Test';
        payloadrequest.UnitCode = 'EA';
        payloadrequest.Quantity = 9;
        payloadrequest.Success = 'true';
        
        req.requestURI = '/services/apexrest/LNPartSync/';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(JSON.serializePretty(payloadrequest));
        
        RestContext.request = req;
        RestContext.response = res;
     
        Test.startTest();

        MSN_RestResourceLNPartSync.updatepartquantity();

        System.assertEquals(400, res.statusCode);
        RestResponse resp = (RestResponse)JSON.deserialize(res.responseBody.toString(), RestResponse.class);
        
        System.assertEquals(MSN_RestResourceLNPartSync.FAILED_MSG, resp.Description);
        System.debug('res : ' + res);
        Test.stopTest();
    } 
}