force-app/main/default/objects/MSN_WorkStepAnswer__c/MSN_WorkStepAnswer__c.object-meta.xml
<CustomObject>
    <description>Used to store the possible answer values (aka &quot;findings&quot;) for a specific Spot question. This is e.g. used in the Field Service Mobile App to present the user with a picklis of possible Answer Values to choose from when answering a Spot Question on a Work Step.</description>
    <label>Work Step Answer Choice</label>
    <nameField>
        <displayFormat>WPA-{0000}</displayFormat>
        <label>Work Plan Answer Choice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Step Answer Choices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MSN_WorkStepAnswer__c/fields/MSN_AnswerValue__c.field-meta.xml
<CustomField>
    <fullName>MSN_AnswerValue__c</fullName>
    <description>Stores the Value of the answer for a specific SPOT question on a Work Step that needs to be sent back to EAM.</description>
    <inlineHelpText>Please enter the Answer value that needs to be sent back to EAM (e.g. Y, N, TPD, NOFLT, PRIPRO)</inlineHelpText>
    <label>Answer Value</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MSN_WorkStepAnswer__c/fields/MSN_Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>MSN_Sort_Order__c</fullName>
    <description>Used to define the order the &quot;Work Step Answer&quot; should show up on the picklist presented to the Field Service Mobile User when answering a Work Step (with the flow &quot;MSN - Field Service Mobile App - Work Step Answers&quot;). Please note that this only reliably works with alphabetical sort values in the mobile app  (a, b, c, d ...) when more than 10 picklist values are present. When using numerical values (1, 2, ...10) then it sorts incorrectly like 1, 10, 2, 3 in the app.</description>
    <inlineHelpText>Please assign an alphabetical letter (a, b, c, ...) to define the sort order of this answer as it is supposed to show up in the picklist for the Field Crew on their Mobile App.</inlineHelpText>
    <label>Alphabetic Sort Order</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MSN_WorkStepAnswer__c/fields/MSN_WorkStepTemplate__c.field-meta.xml
<CustomField>
    <fullName>MSN_WorkStepTemplate__c</fullName>
    <description>Master-Detail Relationship between a Work Step Answer and the parent &quot;Work Step Template&quot; it relates to.</description>
    <label>Work Step Template</label>
    <referenceTo>WorkStepTemplate</referenceTo>
    <relationshipName>Work_Step_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MSN_WorkStepAnswerTriggerHelper.cls
/**
 * @File Name          : MSN_WorkStepAnswerTriggerHelper.cls
 * @Description        : Trigger Helper for WorkStepAnswer__c
 * @Author             : David Azzi
 * @Group              : 
 * @Last Modified By   : David Azzi
 * @Last Modified On   : 13/01/2022
 * @Modification Log   : 
 * Ver      Date            Author                  Modification
 * 1.0      01/12/2021      David Azzi              Initial Version
**/
public class MSN_WorkStepAnswerTriggerHelper {
    // commented out because none of method has been used    
    //1 Select
    /*public static Map<Id, List<MSN_WorkStepAnswer__c>> getAllRelatedWSAs(List<MSN_WorkStepAnswer__c> newWSA)
    {   
        Map<Id, List<MSN_WorkStepAnswer__c>> output = new Map<Id, List<MSN_WorkStepAnswer__c>>();
        List<MSN_WorkStepAnswer__c> relatedWSAs = new List<MSN_WorkStepAnswer__c>(newWSA);
        Set<Id> wstIds = new Set<Id>();

        for ( MSN_WorkStepAnswer__c wsa : newWSA )
        {
            wstIds.add(wsa.MSN_WorkStepTemplate__c);
        }

        relatedWSAs.addAll([SELECT MSN_WorkStepTemplate__c, MSN_AnswerValue__c, MSN_Sort_Order__c FROM MSN_WorkStepAnswer__c WHERE MSN_WorkStepTemplate__c IN: wstIds]);

        for ( MSN_WorkStepAnswer__c wsa : relatedWSAs ){
            if ( output.containsKey(wsa.MSN_WorkStepTemplate__c) )
            {
                output.get(wsa.MSN_WorkStepTemplate__c).add(wsa);
            } else {
                output.put(wsa.MSN_WorkStepTemplate__c, new List<MSN_WorkStepAnswer__c>{wsa});
            }
        }
        
        return output;
    }


    public static void updateSortAllWSA(List<MSN_WorkStepAnswer__c> newWSAs)
    {
        Map<Id, List<MSN_WorkStepAnswer__c>> wstIdWSAs = getAllRelatedWSAs(newWSAs);
        
        List<MSN_WorkStepAnswer__c> lstToUpdate = new List<MSN_WorkStepAnswer__c>();
        for(Id wstId : wstIdWSAs.keySet())
        {
            List<MSN_WorkStepAnswer__c> wsas = wstIdWSAs.get(wstId);
            Map<String, List<MSN_WorkStepAnswer__c>> wsaAnswerValueWSA = new Map<String, List<MSN_WorkStepAnswer__c>>();
            List<MSN_WorkStepAnswer__c> wsaNumericList = new List<MSN_WorkStepAnswer__c>();
            List<MSN_WorkStepAnswer__c> wsaSortedList = new List<MSN_WorkStepAnswer__c>();

            for ( MSN_WorkStepAnswer__c wsa : wsas)
            {
                if ( wsa.MSN_AnswerValue__c.isNumeric() )
                {
                    wsaNumericList.add(wsa);
                } else {
                    if (wsaAnswerValueWSA.containsKey(wsa.MSN_AnswerValue__c) )
                    {
                        wsaAnswerValueWSA.get(wsa.MSN_AnswerValue__c).add(wsa);
                    } else {
                        wsaAnswerValueWSA.put(wsa.MSN_AnswerValue__c, new List<MSN_WorkStepAnswer__c>{wsa});
                    }
                }
            }

            System.debug(wsaNumericList.size());
            //insertion sort
            for(Integer i = 1; i < wsaNumericList.size(); i++)
            {
                MSN_WorkStepAnswer__c wsaKey = wsaNumericList[i];

                Integer j = i - 1;

                while( j >= 0 && Integer.valueOf(wsaNumericList[j].MSN_AnswerValue__c) > Integer.valueOf(wsaKey.MSN_AnswerValue__c))
                {
                    wsaNumericList[j + 1] = wsaNumericList[j];
                    j = j - 1;
                }
                wsaNumericList[j+1] = wsaKey;
            }

            //numeric first
            wsaSortedList.addAll(wsaNumericList);

            //alpha last - Lists are already sorted by in-built Map
            for(String values : wsaAnswerValueWSA.keySet())
            {
                wsaSortedList.addAll(wsaAnswerValueWSA.get(values));
            }

            System.debug(wsaSortedList);
            lstToUpdate.addAll(addAlphaToSortedList(wsaSortedList));
        }

        for(MSN_WorkStepAnswer__c wsa : lstToUpdate){
            System.debug(wsa.MSN_Sort_Order__c);
        }
        System.debug(lstToUpdate);
    }

    public static List<MSN_WorkStepAnswer__c> addAlphaToSortedList(List<MSN_WorkStepAnswer__c> wsas)
    {

        for(Integer i = 0; i < wsas.size(); i++) {
            wsas[i].MSN_Sort_Order__c = convertNumberToSortString(i);
        }
        return wsas;
    }

    public static String getLetterOfIndex(Integer letterIndex){

        List<String> hex = new List<String>{'0','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'};       
        return hex[letterIndex];
    }

    //Examples: 1 == A     27 == AA     1367 == AZO
    public static String convertNumberToSortString(Integer num){
        Integer rem = num;

        String output = '';

        while (rem > 0 ){
            Integer numberToLetter = Math.mod(rem,26);
            numberToLetter = (numberToLetter == 0 ) ? 26 : numberToLetter;
            rem = (rem - numberToLetter) / 26;
            output = getLetterOfIndex(numberToLetter) + output;
        }

        return output;
    }*/
}