force-app/main/default/objects/Asset/fields/Comp_Key__c.field-meta.xml
<CustomField>
    <fullName>Comp_Key__c</fullName>
    <description>Source field is Asset Key from EAM, 8 digit number.</description>
    <externalId>true</externalId>
    <label>Comp Key</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Work_Step_Answer_Mapping__c/Work_Step_Answer_Mapping__c.object-meta.xml
<CustomObject>
    <description>MSRS-231

Custom Object to be used as a junction-type object between Work Step Answers and SPOT Code Mappings. This object is used to pre-fill Work Step Answers by recording spot codes and required object/fields.</description>
    <label>Work Step Answer Mapping</label>
    <nameField>
        <label>Work Step Answer Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Step Answer Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Step_Answer_Mapping__c/fields/MSN_FROM_Object__c.field-meta.xml
<CustomField>
    <fullName>MSN_FROM_Object__c</fullName>
    <description>Is used to define, from which object to retrieve information from that should be prepopulated into the &quot;Work Step Answer&quot;</description>
    <inlineHelpText>Please enter the API Name of the object you would like to retrieve the prepopulated answer from</inlineHelpText>
    <label>Prepopulated Answer - Object Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asset</fullName>
                <default>true</default>
                <label>Asset</label>
            </value>
            <value>
                <fullName>ServiceAppointment</fullName>
                <label>Service Appointment</label>
            </value>
            <value>
                <fullName>WorkOrder</fullName>
                <label>Work Order</label>
            </value>
            <value>
                <fullName>WorkOrderLineItem</fullName>
                <label>Work Order Line Item</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Step_Answer_Mapping__c/fields/MSN_FROM_Object_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>MSN_FROM_Object_Field_API_Name__c</fullName>
    <description>This must be the API name of the FIELD that is on the object listed in the FROM OBJECT</description>
    <inlineHelpText>Please enter the API Name of the FIELD that is on the object listed in the &quot;FROM Object&quot; field in order to prepopulate that information into the &quot;Work Step Answer&quot; field</inlineHelpText>
    <label>Prepopulated Answer - Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Step_Answer_Mapping__c/fields/MSN_SPOT_Code__c.field-meta.xml
<CustomField>
    <fullName>MSN_SPOT_Code__c</fullName>
    <formula>MSN_Work_Step_Template__r.MSN_SPOT_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SPOT Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Step_Answer_Mapping__c/fields/MSN_Work_Step_Template__c.field-meta.xml
<CustomField>
    <fullName>MSN_Work_Step_Template__c</fullName>
    <description>Links the Work Step Answer Mapping to its parent Work Step Template</description>
    <label>Work Step Template</label>
    <referenceTo>WorkStepTemplate</referenceTo>
    <relationshipLabel>Work Step Answer Mappings</relationshipLabel>
    <relationshipName>Work_Step_Answer_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <formula>IF( Asset.SerialNumber &lt;&gt; null, Asset.SerialNumber, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Serial Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Work_Order_No__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_No__c</fullName>
    <description>https://watercarestp.atlassian.net/browse/MSRS-93</description>
    <externalId>true</externalId>
    <label>EAM Work Order Number</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WorkOrder/recordTypes/MSN.recordType-meta.xml
<RecordType>
    <fullName>MSN</fullName>
    <active>true</active>
    <description>Please use this for all normal planned or reactive work (NOT reinstatement)</description>
    <label>MSN</label>
</RecordType>

force-app/main/default/objects/WorkStep/fields/MSN_Answer_Type__c.field-meta.xml
<CustomField>
    <fullName>MSN_Answer_Type__c</fullName>
    <description>Used to define the Type of Answer that is expected for this Work Step (e.g. String, Date, Boolean, Picklist , URL). Please note: If &quot;Picklist&quot; is chosen, at least 2 &quot;Work Step Answers&quot; have to be added to this Work Step Template. If &quot;URL&quot; is chose, you have to populate a URL into the field &quot;External URL&quot; on the Work Step Template.</description>
    <inlineHelpText>Defines what type of answer is expected for this Work Step.</inlineHelpText>
    <label>Answer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSN_Work_Steps_Field_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkStep/fields/MSN_SPOT_Code__c.field-meta.xml
<CustomField>
    <fullName>MSN_SPOT_Code__c</fullName>
    <description>SPOT Codes are used by MSN/Watercare in subsequent systems (e.g. finance and GIS) for invoicing and asset records.</description>
    <externalId>true</externalId>
    <inlineHelpText>Please enter the SPOT code that should be applied for this work step (e.g. 1060).</inlineHelpText>
    <label>SPOT Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkStep/fields/MSN_WorkStep_Answer__c.field-meta.xml
<CustomField>
    <fullName>MSN_WorkStep_Answer__c</fullName>
    <description>Used to record the Answer that has been given to a Work Step question via the Flow &quot;MSN - Field Service Mobile App - Work Step Answers&quot; as part of a Work Plan for a given Work Order.</description>
    <label>Work Step Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkStepTemplate/fields/MSN_Answer_Type__c.field-meta.xml
<CustomField>
    <fullName>MSN_Answer_Type__c</fullName>
    <description>Used to define the Type of Answer that is expected for this Work Step (e.g. String, Date, Boolean, Picklist , URL). Please note: If &quot;Picklist&quot; is chosen, at least 2 &quot;Work Step Answers&quot; have to be added to this Work Step Template. If &quot;URL&quot; is chose, you have to populate a URL into the field &quot;External URL&quot; on the Work Step Template.</description>
    <inlineHelpText>Please specify what type of answer you expect for this Work Step. If you choose &quot;Picklist&quot;, you have to add at least two &quot;Work Step Answers&quot; to this template in order to show the user those as picklist choices. If you select &quot;URL&quot; you have to populate the &quot;External URL&quot; field on the record  - e.g. a link to Powerapps.</inlineHelpText>
    <label>Answer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSN_Work_Steps_Field_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkStepTemplate/fields/MSN_WorkStep_Answer__c.field-meta.xml
<CustomField>
    <fullName>MSN_WorkStep_Answer__c</fullName>
    <description>Used to record the Answer that has been given to a Work Step question via the Flow &quot;MSN - Field Service Mobile App - Work Step Answers&quot; as part of a Work Plan for a given Work Order.</description>
    <inlineHelpText>If you type in an answer on this Work Step Template, this will then show up as a prepopulated answer on the Work Step for the mobile user.</inlineHelpText>
    <label>Work Step Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkType/fields/MSN_ActivityCode__c.field-meta.xml
<CustomField>
    <fullName>MSN_ActivityCode__c</fullName>
    <description>Used to capture the Activity Code in EAM that is related to this Work Type (eg WMTPMR).</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter the equivalent &quot;Activity Code&quot; from EAM that relates to this Work Type (eg WMTPMR).</inlineHelpText>
    <label>Activity Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MSN_WorkStepTriggerHelper_Test.cls
/**
 * @File Name          : MSN_WorkStepTriggerHelper_Test.cls
 * @Description        : Test class for MSN_WorkStepTriggerHelper.cls
 * @Author             : Bohao Chen
 * Ver      Date            Author                  Modification
 * 1.0      23/01/2023      Bohao Chen           Initial Version
**/
@isTest
public class MSN_WorkStepTriggerHelper_Test {
    @TestSetup
    static void testDataSetup() {
        ServiceTerritory st = (ServiceTerritory)TestDataFactory.createSObject('ServiceTerritory', new Map<String,Object>{
            'IsActive' => true
        });

        WorkType wt = (WorkType)TestDataFactory.createSObject('WorkType', new Map<String,Object>{
            'MSN_ActivityCode__c' => 'abcd'
        });

        Asset asset = (Asset)TestDataFactory.createSObject('Asset', new Map<String,Object>{
            'Comp_Key__c' => '555',
            'SerialNumber' => '55555'
        });

        WorkStepTemplate wsTemplate = (WorkStepTemplate)TestDataFactory.createSObject('WorkStepTemplate', new Map<String,Object>{
            'MSN_SPOT_Code__c' => 'W2010',
            'MSN_Answer_Type__c' => 'String',
            'IsActive' => true,
            'Description' => 'What is the ID of the old water meter?'
        });

        Work_Step_Answer_Mapping__c wsm = (Work_Step_Answer_Mapping__c)TestDataFactory.createSObject('Work_Step_Answer_Mapping__c', new Map<String,Object>{
            'MSN_FROM_Object__c' => 'WorkOrder',
            'MSN_FROM_Object_Field_API_Name__c' => 'Serial_Number__c',
            'MSN_Work_Step_Template__c' => wsTemplate.Id
        });

        Id msnWorkOrderRtId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('MSN').getRecordTypeId();        
        
        // create a new work order
        WorkOrder wo = (WorkOrder)TestDataFactory.createSObject('WorkOrder', new Map<String,Object>{
            'ServiceTerritoryId' =>  st.Id,
            'WorkTypeId' => wt.Id,
            'Status' => 'New',
            'recordTypeId' => msnWorkOrderRtId,
            'Work_Order_No__c' => '123456',
            'Street' => '44 Meadowbank Road', 
            'PostalCode' => '1072', 
            'Country' => 'New Zealand', 
            'City' => 'Auckland', 
            'Priority' => '7',
            'AssetId' => asset.Id
        });
    }

    static testMethod void successWorkStepTest() {

        Id woId = [SELECT Id FROM WorkOrder LIMIT 1].Id;
        Id wstId = [SELECT Id FROM WorkStepTemplate LIMIT 1].Id;

        WorkPlan wp = (WorkPlan)TestDataFactory.createSObject('WorkPlan', new Map<String,Object>{
            'ParentRecordId' => woId
        });

        Test.startTest();
        WorkStep ws = (WorkStep)TestDataFactory.createSObject('WorkStep', new Map<String,Object>{
            'MSN_WorkStep_Answer__c' => '',
            'MSN_SPOT_Code__c' => 'W2010',
            'WorkPlanId' => wp.Id
        });
        Test.stopTest();

        ws = [SELECT MSN_WorkStep_Answer__c FROM WorkStep WHERE WorkOrderId =: woId];
        System.assertEquals('55555', ws.MSN_WorkStep_Answer__c);
        


    }
}