force-app/main/default/objects/Asset/fields/Comp_Key__c.field-meta.xml
<CustomField>
    <fullName>Comp_Key__c</fullName>
    <description>Source field is Asset Key from EAM, 8 digit number.</description>
    <externalId>true</externalId>
    <label>Comp Key</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductConsumed/fields/Not_Sufficient_EAM_Stock__c.field-meta.xml
<CustomField>
    <fullName>Not_Sufficient_EAM_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Not Sufficient EAM Stock</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProductConsumed/fields/Previous_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Previous_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Previous Quantity</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductConsumed/fields/Sent_to_EAM__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_EAM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent to EAM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProductItem/fields/EAM_Quantity__c.field-meta.xml
<CustomField>
    <fullName>EAM_Quantity__c</fullName>
    <description>stock levels from EAM</description>
    <label>EAM Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Work_Order_No__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_No__c</fullName>
    <description>https://watercarestp.atlassian.net/browse/MSRS-93</description>
    <externalId>true</externalId>
    <label>EAM Work Order Number</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WorkOrder/recordTypes/MSN.recordType-meta.xml
<RecordType>
    <fullName>MSN</fullName>
    <active>true</active>
    <description>Please use this for all normal planned or reactive work (NOT reinstatement)</description>
    <label>MSN</label>
</RecordType>

force-app/main/default/objects/WorkType/fields/MSN_ActivityCode__c.field-meta.xml
<CustomField>
    <fullName>MSN_ActivityCode__c</fullName>
    <description>Used to capture the Activity Code in EAM that is related to this Work Type (eg WMTPMR).</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter the equivalent &quot;Activity Code&quot; from EAM that relates to this Work Type (eg WMTPMR).</inlineHelpText>
    <label>Activity Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MSN_ProductConsumedTriggerHelper_Test.cls
/**
 * @File Name          : MSN_ProductConsumedTriggerHelper_Test.cls
 * @Description        : Test class for MSN_ProductConsumedTriggerHelper.cls
 * @Author             : Bohao Chen
 * Ver      Date            Author                  Modification
 * 1.0      31/01/2023      Bohao Chen           Initial Version
**/
@isTest
public class MSN_ProductConsumedTriggerHelper_Test {
    @TestSetup
    static void testDataSetup() {

        ServiceTerritory st = (ServiceTerritory)TestDataFactory.createSObject('ServiceTerritory', new Map<String,Object>{
            'IsActive' => true
        });

        WorkType wt = (WorkType)TestDataFactory.createSObject('WorkType', new Map<String,Object>{
            'MSN_ActivityCode__c' => 'abcd'
        });

        Asset asset = (Asset)TestDataFactory.createSObject('Asset', new Map<String,Object>{
            'Comp_Key__c' => '555'
        });

        Product2 product = (Product2)TestDataFactory.createSObject('Product2', new Map<String,Object>{
            'Name' => 'Testing Part',
            'IsActive' => true,
            'ProductCode' => 'abcd'
        });

        Product2 labourCharge = (Product2)TestDataFactory.createSObject('Product2', new Map<String,Object>{
            'Name' => 'Labour Charge',
            'IsActive' => true,
            'ProductCode' => 'Labour',
            'Family' => 'Labour'
        });

        String standardPricebookId = Test.getStandardPricebookId();

        PricebookEntry pe = (PricebookEntry)TestDataFactory.createSObject('PricebookEntry', new Map<String,Object>{
            'Pricebook2Id' => standardPricebookId,
            'Product2Id' => labourCharge.Id,
            'IsActive' => true,
            'UnitPrice' => 1
        });

        Schema.Location l = new Schema.Location();
        l.LocationType = 'Van';
        l.IsInventoryLocation = true;
        l.Name = 'van location';
        insert l;
        // )TestDataFactory.createSObject('System.Location', new Map<String,Object>{
        //     'LocationType' => 'Van',
        //     'IsInventoryLocation' => true            
        // });

        ProductItem productItem = (ProductItem)TestDataFactory.createSObject('ProductItem', new Map<String,Object>{
            'EAM_Quantity__c' => 6,
            'Product2Id' => product.Id,
            'LocationId' => l.Id,
            'QuantityOnHand' => 6
        });

        Id msnWorkOrderRtId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('MSN').getRecordTypeId();

        // create work order
        WorkOrder wo = (WorkOrder)TestDataFactory.createSObject('WorkOrder', new Map<String,Object>{
            'ServiceTerritoryId' =>  st.Id,
            'WorkTypeId' => wt.Id,
            'Status' => 'New',
            'recordTypeId' => msnWorkOrderRtId,
            'Work_Order_No__c' => '123456',
            'Street' => '44 Meadowbank Road', 
            'PostalCode' => '1072', 
            'Country' => 'New Zealand', 
            'City' => 'Auckland', 
            'Priority' => '7',
            'Pricebook2Id' => standardPricebookId
        });

    }

    static testMethod void insertProductConsumedQuantityTest() {

        WorkOrder wo = [SELECT Id FROM WorkOrder LIMIT 1];
        ProductItem pi = [SELECT Id FROM ProductItem LIMIT 1];

        Test.startTest();
        ProductConsumed stm = (ProductConsumed)TestDataFactory.createSObject('ProductConsumed', new Map<String,Object>{
            'WorkOrderId' => wo.Id,
            'QuantityConsumed' => 1,
            'Sent_to_EAM__c' => false,
            'ProductItemId' => pi.Id,
            'Not_Sufficient_EAM_Stock__c' => false
        });
        Test.stopTest();
    }

    static testMethod void insertLabourChargeTest() {

        WorkOrder wo = [SELECT Id FROM WorkOrder LIMIT 1];
        ProductItem pi = [SELECT Id FROM ProductItem LIMIT 1];
        Product2 labourCharge = [SELECT Id FROM Product2 WHERE Name = 'Labour Charge'];
        PricebookEntry pe = [SELECT Id FROM PricebookEntry];

        Test.startTest();
        ProductConsumed stm = (ProductConsumed)TestDataFactory.createSObject('ProductConsumed', new Map<String,Object>{
            'WorkOrderId' => wo.Id,
            'QuantityConsumed' => 1,
            'Sent_to_EAM__c' => false,
            'PricebookEntryId' => pe.Id,
            // 'ProductItemId' => pi.Id,
            'Not_Sufficient_EAM_Stock__c' => false
        });
        Test.stopTest();
    }

    static testMethod void increaseProductConsumedQuantityTest() {

        WorkOrder wo = [SELECT Id FROM WorkOrder LIMIT 1];
        ProductItem pi = [SELECT Id FROM ProductItem LIMIT 1];

        
        ProductConsumed stm = (ProductConsumed)TestDataFactory.createSObject('ProductConsumed', new Map<String,Object>{
            'WorkOrderId' => wo.Id,
            'QuantityConsumed' => 1,
            'Sent_to_EAM__c' => true,
            'Previous_Quantity__c' => 0,
            'ProductItemId' => pi.Id,
            'Not_Sufficient_EAM_Stock__c' => false
        });

        Test.startTest();
        stm.Previous_Quantity__c = 1;
        stm.QuantityConsumed = 2;
        stm.Sent_to_EAM__c = false;
        update stm;
        Test.stopTest();
    }

    static testMethod void updateLabourChargeTest() {

        WorkOrder wo = [SELECT Id FROM WorkOrder LIMIT 1];
        ProductItem pi = [SELECT Id FROM ProductItem LIMIT 1];
        Product2 labourCharge = [SELECT Id FROM Product2 WHERE Name = 'Labour Charge'];
        PricebookEntry pe = [SELECT Id FROM PricebookEntry];

        
        ProductConsumed stm = (ProductConsumed)TestDataFactory.createSObject('ProductConsumed', new Map<String,Object>{
            'WorkOrderId' => wo.Id,
            'QuantityConsumed' => 1,
            'Sent_to_EAM__c' => false,
            'PricebookEntryId' => pe.Id,
            // 'ProductItemId' => pi.Id,
            'Not_Sufficient_EAM_Stock__c' => false
        });

        Test.startTest();
        stm.QuantityConsumed = 2;
        stm.Sent_to_EAM__c = false;
        update stm;
        Test.stopTest();
    }

    static testMethod void decreaseProductConsumedQuantityTest() {
        WorkOrder wo = [SELECT Id FROM WorkOrder LIMIT 1];
        ProductItem pi = [SELECT Id FROM ProductItem LIMIT 1];

        
        ProductConsumed stm = (ProductConsumed)TestDataFactory.createSObject('ProductConsumed', new Map<String,Object>{
            'WorkOrderId' => wo.Id,
            'QuantityConsumed' => 3,
            'Sent_to_EAM__c' => true,
            'Previous_Quantity__c' => 0,
            'ProductItemId' => pi.Id,
            'Not_Sufficient_EAM_Stock__c' => false
        });

        Test.startTest();
        stm.Previous_Quantity__c = 3;
        stm.QuantityConsumed = 1;
        stm.Sent_to_EAM__c = false;
        update stm;
        Test.stopTest();

    }

    static testMethod void deleteProductConsumedQuantityTest() {

        WorkOrder wo = [SELECT Id FROM WorkOrder LIMIT 1];
        ProductItem pi = [SELECT Id FROM ProductItem LIMIT 1];

        
        ProductConsumed stm = (ProductConsumed)TestDataFactory.createSObject('ProductConsumed', new Map<String,Object>{
            'WorkOrderId' => wo.Id,
            'QuantityConsumed' => 3,
            'Sent_to_EAM__c' => true,
            'ProductItemId' => pi.Id,
            'Not_Sufficient_EAM_Stock__c' => false
        });

        Test.startTest();
        delete stm;
        Test.stopTest();
    }

    static testMethod void deleteLabourChargeTest() {

        WorkOrder wo = [SELECT Id FROM WorkOrder LIMIT 1];
        ProductItem pi = [SELECT Id FROM ProductItem LIMIT 1];
        Product2 labourCharge = [SELECT Id FROM Product2 WHERE Name = 'Labour Charge'];
        PricebookEntry pe = [SELECT Id FROM PricebookEntry];

        
        ProductConsumed stm = (ProductConsumed)TestDataFactory.createSObject('ProductConsumed', new Map<String,Object>{
            'WorkOrderId' => wo.Id,
            'QuantityConsumed' => 1,
            'Sent_to_EAM__c' => false,
            'PricebookEntryId' => pe.Id,
            // 'ProductItemId' => pi.Id,
            'Not_Sufficient_EAM_Stock__c' => false
        });

        Test.startTest();
        delete stm;
        Test.stopTest();
    }
}