force-app/main/default/objects/Asset/fields/Comp_Key__c.field-meta.xml
<CustomField>
    <fullName>Comp_Key__c</fullName>
    <description>Source field is Asset Key from EAM, 8 digit number.</description>
    <externalId>true</externalId>
    <label>Comp Key</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MSN_JobNotes__c/MSN_JobNotes__c.object-meta.xml
<CustomObject>
    <description>Used to capture Job Notes from the mobile field crew that need to be sent back into EAM.</description>
    <label>Job Note</label>
    <nameField>
        <displayFormat>JBN-{00000}</displayFormat>
        <label>Job Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MSN_JobNotes__c/fields/Dialysis_Patient__c.field-meta.xml
<CustomField>
    <fullName>Dialysis_Patient__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dialysis Patient</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MSN_JobNotes__c/fields/MSN_EAM_Work_Order_No__c.field-meta.xml
<CustomField>
    <fullName>MSN_EAM_Work_Order_No__c</fullName>
    <description>populate EAM work order number from either work order or work order line item for the job note payload</description>
    <formula>IF( ISBLANK(Work_Order_Line_Item__c), MSN_Work_Order__r.Work_Order_No__c ,  Work_Order_Line_Item__r.MSN_EAM_Work_Order_No__c )</formula>
    <label>EAM Work Order Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MSN_JobNotes__c/fields/MSN_JobNote_Details__c.field-meta.xml
<CustomField>
    <fullName>MSN_JobNote_Details__c</fullName>
    <description>Stores the actual Job Note eg entered by the field crew from the mobile app.</description>
    <label>Note Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MSN_JobNotes__c/fields/Service_Request_Update_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Request_Update_Code__c</fullName>
    <label>Service Request Update Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Comp_Key__c.field-meta.xml
<CustomField>
    <fullName>Comp_Key__c</fullName>
    <formula>FSSK__FSK_Work_Order__r.Asset.Comp_Key__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Comp Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Confined_space_entry__c.field-meta.xml
<CustomField>
    <fullName>Confined_space_entry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confined space entry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Crew_out_of_confined_space__c.field-meta.xml
<CustomField>
    <fullName>Crew_out_of_confined_space__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Crew out of confined space</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Dialysis_Patient__c.field-meta.xml
<CustomField>
    <fullName>Dialysis_Patient__c</fullName>
    <description>https://watercarestp.atlassian.net/browse/MSRS-93</description>
    <formula>FSSK__FSK_Work_Order__r.Dialysis_Patient__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dialysis Patient</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/MSN_TravelStart__c.field-meta.xml
<CustomField>
    <fullName>MSN_TravelStart__c</fullName>
    <description>Used to capture the Date/Time when a field crew starts travelling to a Service Appointments (=updates the field &quot;Status&quot; on Service Appointment to &quot;Travel&quot; via the FSL Mobile App)</description>
    <label>Travel Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>P1</fullName>
            </value>
            <value>
                <fullName>P2</fullName>
            </value>
            <value>
                <fullName>P3</fullName>
            </value>
            <value>
                <fullName>P4</fullName>
            </value>
            <value>
                <fullName>P5</fullName>
            </value>
            <value>
                <fullName>P6</fullName>
            </value>
            <value>
                <fullName>P7</fullName>
            </value>
            <value>
                <fullName>P8</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Dialysis_Patient__c.field-meta.xml
<CustomField>
    <fullName>Dialysis_Patient__c</fullName>
    <defaultValue>false</defaultValue>
    <description>https://watercarestp.atlassian.net/browse/MSRS-93</description>
    <label>Dialysis Patient</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Estimated_Water_On__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Water_On__c</fullName>
    <label>Estimated Water On Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Work_Order_No__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_No__c</fullName>
    <description>https://watercarestp.atlassian.net/browse/MSRS-93</description>
    <externalId>true</externalId>
    <label>EAM Work Order Number</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WorkOrder/recordTypes/MSN.recordType-meta.xml
<RecordType>
    <fullName>MSN</fullName>
    <active>true</active>
    <description>Please use this for all normal planned or reactive work (NOT reinstatement)</description>
    <label>MSN</label>
</RecordType>

force-app/main/default/objects/WorkStep/fields/MSN_Answer_Type__c.field-meta.xml
<CustomField>
    <fullName>MSN_Answer_Type__c</fullName>
    <description>Used to define the Type of Answer that is expected for this Work Step (e.g. String, Date, Boolean, Picklist , URL). Please note: If &quot;Picklist&quot; is chosen, at least 2 &quot;Work Step Answers&quot; have to be added to this Work Step Template. If &quot;URL&quot; is chose, you have to populate a URL into the field &quot;External URL&quot; on the Work Step Template.</description>
    <inlineHelpText>Defines what type of answer is expected for this Work Step.</inlineHelpText>
    <label>Answer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSN_Work_Steps_Field_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkStep/fields/MSN_WorkStep_Answer__c.field-meta.xml
<CustomField>
    <fullName>MSN_WorkStep_Answer__c</fullName>
    <description>Used to record the Answer that has been given to a Work Step question via the Flow &quot;MSN - Field Service Mobile App - Work Step Answers&quot; as part of a Work Plan for a given Work Order.</description>
    <label>Work Step Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkType/fields/MSN_ActivityCode__c.field-meta.xml
<CustomField>
    <fullName>MSN_ActivityCode__c</fullName>
    <description>Used to capture the Activity Code in EAM that is related to this Work Type (eg WMTPMR).</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter the equivalent &quot;Activity Code&quot; from EAM that relates to this Work Type (eg WMTPMR).</inlineHelpText>
    <label>Activity Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MSN_JobNoteUtility_Test.cls
/**
 * @File Name          : MSN_JobNoteUtility_Test.cls
 * @Description        : Test class for MSN_JobNoteUtility.cls
 * @Author             : Bohao Chen
 * Ver      Date            Author                  Modification
 * 1.0      30/01/2023      Bohao Chen           Initial Version
**/
@isTest
public class MSN_JobNoteUtility_Test {
    @TestSetup
    static void testDataSetup() {
        ServiceTerritory st = (ServiceTerritory)TestDataFactory.createSObject('ServiceTerritory', new Map<String,Object>{
            'IsActive' => true
        });

        WorkType wt = (WorkType)TestDataFactory.createSObject('WorkType', new Map<String,Object>{
            'MSN_ActivityCode__c' => 'abcd'
        });

        Asset asset = (Asset)TestDataFactory.createSObject('Asset', new Map<String,Object>{
            'Comp_Key__c' => '555'
        });

        Id msnWorkOrderRtId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('MSN').getRecordTypeId();

        // create work order
        WorkOrder wo = (WorkOrder)TestDataFactory.createSObject('WorkOrder', new Map<String,Object>{
            'ServiceTerritoryId' =>  st.Id,
            'WorkTypeId' => wt.Id,
            'Status' => 'New',
            'recordTypeId' => msnWorkOrderRtId,
            'Work_Order_No__c' => '123456',
            'Street' => '44 Meadowbank Road', 
            'PostalCode' => '1072', 
            'Country' => 'New Zealand', 
            'City' => 'Auckland', 
            'Priority' => '7'
        });

        WorkPlan wp = (WorkPlan)TestDataFactory.createSObject('WorkPlan', new Map<String,Object>{
            'ParentRecordId' => wo.Id,
            'WorkOrderId' => wo.Id
        });

        WorkStep workStep = (WorkStep)TestDataFactory.createSObject('WorkStep', new Map<String, Object>{
            'WorkPlanId' => wp.Id,
            'MSN_Answer_Type__c' => 'Schedule Item Code'
        });

        FSL__Scheduling_Policy__c schPolicy = (FSL__Scheduling_Policy__c)TestDataFactory.createSObject('FSL__Scheduling_Policy__c');        

        // create service appointment for work order
        ServiceAppointment sa = (ServiceAppointment)TestDataFactory.createSObject('ServiceAppointment', new Map<String,Object>{
            'ParentRecordId' => wo.Id,
            'EarliestStartTime' => Datetime.now().addHours(-2),
            'SchedStartTime' => Datetime.now(),
            'SchedEndTime' => Datetime.now().addDays(2),
            'Street' => '26 Phyllis ST',
            'City' => 'Mount Albert',
            'Country' => 'New Zealand',
            'PostalCode' => '3127',
            'ServiceTerritoryId' => st.Id,
            'DueDate' => Date.today().addDays(2),
            'Confined_space_entry__c' => false,
            'Crew_out_of_confined_space__c' => false,
            // 'Dialysis_Patient__c' => false,
            'FSL__Scheduling_Policy_Used__c' => schPolicy.Id,
            'Priority__c' => 'P7',
            'Status' => 'Dispatched'
            // 'ActualStartTime' => Datetime.now(),
            // 'MSN_TravelStart__c' => Datetime.now(),
            // 'ActualEndTime' => Datetime.now().addDays(1)
        });

        // create service resource
        Profile p = [SELECT Id FROM Profile WHERE Name = 'MSN Field Crew'];

        // create a user for service resource
        User user = (User)TestDataFactory.createSObject('User', new Map<String,Object>{
            'ProfileId' => p.Id,
            'Username' => 'test@HGUBHJHGTU.com'
        });
        
        // create service resources for sa
        ServiceResource sr = (ServiceResource)TestDataFactory.createSObject('ServiceResource', new Map<String,Object>{
            'RelatedRecordId' => user.Id,
            'IsActive' => true
        });

        // create new ST member
        ServiceTerritoryMember stm = (ServiceTerritoryMember)TestDataFactory.createSObject('ServiceTerritoryMember', new Map<String,Object>{
            'ServiceResourceId' => sr.Id,
            'ServiceTerritoryId' => st.Id,
            'TerritoryType' => 'P'
        });

        // create an assigned service resource for service appointment
        AssignedResource ar = (AssignedResource)TestDataFactory.createSObject('AssignedResource', new Map<String,Object>{
            'ServiceResourceId' => sr.Id,
            'ServiceAppointmentId' => sa.Id
        });
    }

    // static testMethod void createJobNotesForServiceAppointmentTest() {        
    //     ServiceAppointment sa = [SELECT Id FROM ServiceAppointment LIMIT 1];        
        
    //     // sa.Status = 'Dispatched';
    //     // update sa;

    //     Test.startTest();
    //     sa.Status = 'Travel'; ///???
    //     update sa;
    //     Test.stopTest();
    // }

    static testMethod void createJobNotesForWorkOrderTest() {
        WorkOrder wo = [SELECT Id, Estimated_Water_On__c FROM WorkOrder WHERE Work_Order_No__c = '123456' LIMIT 1];
        Test.startTest();
        wo.Estimated_Water_On__c = Datetime.now().addDays(1);
        update wo;
        Test.stopTest();

        // assertion
        MSN_JobNotes__c jn = [SELECT Id, MSN_JobNote_Details__c FROM MSN_JobNotes__c 
                            WHERE MSN_EAM_Work_Order_No__c = '123456' 
                            AND Service_Request_Update_Code__c = 'WAON'];
                            
        Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('WorkOrder').getDescribe().fields.getMap();
        wo = [SELECT Estimated_Water_On__c FROM WorkOrder LIMIT 1];
        String valueStr = MSN_JobNoteUtility.convertValueToStr(wo, 'Estimated_Water_On__c', fieldMap);
        System.assertEquals('Estimated Water On Time:' + valueStr, jn.MSN_JobNote_Details__c);
    }

    static testMethod void createJobNotesForWorkStepTest() {

        WorkStep workStep = [SELECT MSN_WorkStep_Answer__c FROM WorkStep LIMIT 1];

        Test.startTest();
        workStep.MSN_WorkStep_Answer__c = 'PRIPRO';
        update workStep;
        Test.stopTest();

        // assertion
    }

    static testMethod void createJobNotesFromJSONTest() {

        MSN_UpdateReactiveMaintenanceWrapper req = new MSN_UpdateReactiveMaintenanceWrapper();
        req.TransactionID = '123';
        req.WorkOrderNo = '123456';
        req.ContractorCode = 'MSN';
        req.UpdateType = 'COMMTW';
        req.UpdateDate = '2019-04-17T12:30:00';
        req.Comments = 'WATERCARE: Hi, the fault that you reported on 52 Mokoia RD on SR15322623 has been repaired. Please allow 15-21 days for reinstatement work to be complete';

        MSN_JobNoteUtility.createJobNote(String.valueOf(JSON.serialize(req)));
        
    }
}