force-app/main/default/objects/Asset/fields/Comp_Key__c.field-meta.xml
<CustomField>
    <fullName>Comp_Key__c</fullName>
    <description>Source field is Asset Key from EAM, 8 digit number.</description>
    <externalId>true</externalId>
    <label>Comp Key</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Outbound_Integration__e/Outbound_Integration__e.object-meta.xml
<CustomObject>
    <description>Platform event to send a message to an AWS Endpoint</description>
    <label>Outbound Integration</label>
    <pluralLabel>Outbound Integration</pluralLabel>
</CustomObject>

force-app/main/default/objects/Outbound_Integration__e/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>EndPoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outbound_Integration__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/EAM_Work_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>EAM_Work_Order_Status__c</fullName>
    <description>work order status from EAM</description>
    <label>EAM Work Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/MSN_Contract__c.field-meta.xml
<CustomField>
    <fullName>MSN_Contract__c</fullName>
    <label>Contract</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Work_Order_No__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_No__c</fullName>
    <description>https://watercarestp.atlassian.net/browse/MSRS-93</description>
    <externalId>true</externalId>
    <label>EAM Work Order Number</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WorkOrder/recordTypes/MSN.recordType-meta.xml
<RecordType>
    <fullName>MSN</fullName>
    <active>true</active>
    <description>Please use this for all normal planned or reactive work (NOT reinstatement)</description>
    <label>MSN</label>
</RecordType>

force-app/main/default/objects/WorkOrderLineItem/fields/EAM_Work_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>EAM_Work_Order_Status__c</fullName>
    <description>This field is used to store the Work Order status from EAM  (e.g. FECO = Field Complete). This is then used to trigger the sending of Costs into the Child Work Order after receiving the status update from EAM.</description>
    <label>EAM Work Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/MSN_Contract__c.field-meta.xml
<CustomField>
    <fullName>MSN_Contract__c</fullName>
    <description>This field is used in the integration to EAM and always needs to be populated when a new work order line record is created ins Salesforce and then sent in the &quot;CreateChildWorkOrder&quot; payload to EAM. It receives its value from the (Root-)Parent Work Order.</description>
    <label>Contract</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/MSN_EAM_Work_Order_No__c.field-meta.xml
<CustomField>
    <fullName>MSN_EAM_Work_Order_No__c</fullName>
    <description>This field is used in integration to reference the EAM Child Work Order Number sent back from EAM when a new Work Order Line Item record is created in Salesforce.</description>
    <externalId>true</externalId>
    <label>EAM Work Order Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/MSN_Root_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>MSN_Root_Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to retrieve the &quot;Root Work Order&quot; from the Parent Work Order related to this WOLI. This is populated in in the Flow &quot;Work Order Line Item - Record Triggered Updates&quot; when a new WOLI is created.</description>
    <label>Root Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Child Work Order Line Items</relationshipLabel>
    <relationshipName>Child_Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/MSN_Work_Line_Number__c.field-meta.xml
<CustomField>
    <fullName>MSN_Work_Line_Number__c</fullName>
    <description>child work order line number</description>
    <displayFormat>WL-{000000}</displayFormat>
    <label>Work Line Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/WorkStep/fields/MSN_Answer_Type__c.field-meta.xml
<CustomField>
    <fullName>MSN_Answer_Type__c</fullName>
    <description>Used to define the Type of Answer that is expected for this Work Step (e.g. String, Date, Boolean, Picklist , URL). Please note: If &quot;Picklist&quot; is chosen, at least 2 &quot;Work Step Answers&quot; have to be added to this Work Step Template. If &quot;URL&quot; is chose, you have to populate a URL into the field &quot;External URL&quot; on the Work Step Template.</description>
    <inlineHelpText>Defines what type of answer is expected for this Work Step.</inlineHelpText>
    <label>Answer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MSN_Work_Steps_Field_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkStep/fields/MSN_SPOT_Code__c.field-meta.xml
<CustomField>
    <fullName>MSN_SPOT_Code__c</fullName>
    <description>SPOT Codes are used by MSN/Watercare in subsequent systems (e.g. finance and GIS) for invoicing and asset records.</description>
    <externalId>true</externalId>
    <inlineHelpText>Please enter the SPOT code that should be applied for this work step (e.g. 1060).</inlineHelpText>
    <label>SPOT Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkStep/fields/MSN_WorkStep_Answer__c.field-meta.xml
<CustomField>
    <fullName>MSN_WorkStep_Answer__c</fullName>
    <description>Used to record the Answer that has been given to a Work Step question via the Flow &quot;MSN - Field Service Mobile App - Work Step Answers&quot; as part of a Work Plan for a given Work Order.</description>
    <label>Work Step Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkType/fields/MSN_ActivityCode__c.field-meta.xml
<CustomField>
    <fullName>MSN_ActivityCode__c</fullName>
    <description>Used to capture the Activity Code in EAM that is related to this Work Type (eg WMTPMR).</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter the equivalent &quot;Activity Code&quot; from EAM that relates to this Work Type (eg WMTPMR).</inlineHelpText>
    <label>Activity Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MSN_WorkOrderLineItemTriggerHelper.cls
/**
 * @File Name          : MSN_WorkOrderLineItemTriggerHelper.cls
 * @Description        : Trigger Helper for WorkOrderLineItem
 * @Author             : David Azzi
 * @Group              : 
 * @Last Modified By   : David Azzi
 * @Last Modified On   : 01/02/2022
 * @Modification Log   : 
 * Ver      Date            Author                  Modification
 * 1.0      01/02/2022      David Azzi              Initial Version
**/
public class MSN_WorkOrderLineItemTriggerHelper {
    
    //get all dispatched items, and recalculate WorkStep answers for Spotcode Mapping
    public static void updateUnansweredWorkPlanAnswers(List<WorkOrderLineItem> newWOLIs)
    {

        Set<Id> woIds = new Set<Id>();
        for(WorkOrderLineItem woli : newWOLIs){
            woIds.add( woli.WorkOrderId );
        }
        
        List<WorkStep> wsteps = [SELECT MSN_WorkStep_Answer__c, WorkOrderId, MSN_SPOT_Code__c
                                FROM WorkStep
                                WHERE WorkOrderId IN: woIds ];

        MSN_WorkStepTriggerHelper.autofillWorkStepAnswer(wsteps);
    }

    public static void callChildWorkOrderToIntegration(Map<Id, WorkOrderLineItem> workOrderLineItemsMap) {
        try {
            List<Outbound_Integration__e> platformEvents = new List<Outbound_Integration__e>();
            String endpoint = 'New_Child_Work_Order';
            platformEvents.addAll(MSN_IntegrationUtility.generateOutboundIntegrationEvents(workOrderLineItemsMap, 'WorkOrderLineItem', 
                new Map<String, List<String>>{endpoint => new String[]{'Create_Child_Work_Order1'}}));

            // publish platform events
            if(!platformEvents.isEmpty()) {
                Id jobId = System.enqueueJob(new MSN_Integration(platformEvents));
                MSN_Integration.integrationQueued = true;
            }
        }catch(Exception e){
            MSN_HandleErrorsException.insertLogException(e, '', '');
        }
    }

   /**
	* Author : Bohao Chen
	* Date : 12/12/2022
	* Description : Created for ticket integration when work order line items are updated
	**/
    public static void updateWorkOrderLineItemIntegration(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
        
        List<WorkOrderLineItem> completedWOLIList = new List<WorkOrderLineItem>();
        List<WorkOrderLineItem> costWOLIList = new List<WorkOrderLineItem>();

        List<WorkOrderLineItem> workOrderLineItemList = [SELECT StartDate,EndDate, MSN_EAM_Work_Order_No__c, Description, 
                                                           Status,MSN_Contract__c, EAM_Work_Order_Status__c,
                                                           WorkOrder.Work_Order_No__c, WorkType.MSN_ActivityCode__c, 
                                                           WorkOrderId, StatusCategory, MSN_Work_Line_Number__c, 
                                                           MSN_Root_Work_Order__r.Work_Order_No__c, Asset.Comp_Key__c,
                                                           MSN_Root_Work_Order__r.StartDate, MSN_Root_Work_Order__r.EndDate,
                                                           CreatedDate
                                                         FROM WorkOrderLineItem WHERE Id IN: newItems.keySet() ];

        for(WorkOrderLineItem newWOLI: workOrderLineItemList) {

            WorkOrderLineItem oldWOLI = (WorkOrderLineItem)oldItems.get(newWOLI.Id);

            if(newWOLI.StatusCategory == 'Completed' && oldWOLI.StatusCategory != 'Completed') {
                completedWOLIList.add(newWOLI);
            }
            
            if(newWOLI.Status == 'Completed' && newWOLI.EAM_Work_Order_Status__c == 'FECO' && oldWOLI.EAM_Work_Order_Status__c != 'FECO') {
                costWOLIList.add(newWOLI);
            }
        }

        // send completed woli (child work order) payload to EAM
        if(!completedWOLIList.isEmpty()) {
            callChildWorkOrderCompleteIntegration(completedWOLIList);
        }

        // send cost payload to EAM
        if(!costWOLIList.isEmpty()) {
            callWorkOrderCostIntegration(costWOLIList);
        }
    }

    /**
	* Author : Bohao Chen
	* Date : 12/12/2022
	* Description : Call the work order (line item) complete integration
	**/
    private static void callChildWorkOrderCompleteIntegration (List<WorkOrderLineItem> completedWOLIList) {
        
        Map<Id,List<WorkStep>> woliIdToWorkStepList = findWorkSteps(completedWOLIList);

        List<sObject> createEventList = new List<sObject>();
        Integration_Endpoint__mdt endpointSetting = MSN_Utility.getEndpointSetting('New_Child_Work_Order');

        if(endpointSetting != null) {
            String endpointStr = endpointSetting.Endpoint__c;

            String method = 'PUT';
            
            for(WorkOrderLineItem woli : completedWOLIList) {
                List<WorkStep> costList = woliIdToWorkStepList.get(woli.Id);
                String payload = createCompletedChildWorkOrderPlayload(costList, woli);
                //String endpoint = 'https://9fa04kq7a0.execute-api.ap-southeast-2.amazonaws.com/dev/v2/maintenance/pmworkorder/'+wo.Work_Order_No__c;
                String endpoint = endpointStr.replace('{workOrderNumber}',woli.MSN_EAM_Work_Order_No__c);
                Outbound_Integration__e platformEvent = new Outbound_Integration__e();
                platformEvent.EndPoint__c = endpoint;
                platformEvent.Method__c = method;
                platformEvent.Payload__c = payload;
                createEventList.add(platformEvent);
            }
            
            // Publishing the events
            try {
                Boolean eventCreation = MSN_GenericPlatformEventUtility.publishEvents(createEventList);
            } catch(Exception e){
                MSN_HandleErrorsException.insertLogException(e, '', '');
            }
        }
    }

    private static Map<Id,List<WorkStep>> findWorkSteps(List<WorkOrderLineItem> completedWOLIList) {

        Set<Id> workOrderIdSet = new Set<Id>();
        Map<Id,List<WorkStep>> woliIdToWorkStepList = new Map<Id,List<WorkStep>>();
        List<sObject> createEventList = new List<sObject>();    
        
        // Loop through wo order to form the Id set
        // for(WorkOrder wo : completeWorkOrderList) {
        //     workOrderIdSet.add(wo.Id);
        // }
        
        List<WorkStep> workStepList = [SELECT WorkOrderLineItemId, MSN_ScheduleItem_Code__c, MSN_SPOT_Code__c,
                                            Description, MSN_WorkStep_Answer__c, LastModifiedDate
                                        FROM WorkStep 
                                        WHERE WorkOrderLineItemId in :completedWOLIList 
                                        AND MSN_Answer_Type__c != 'Schedule Item Code'];
        
        // Form the work order id to work step list
        for(WorkStep step:workStepList) {
            System.debug('step: '+step);
            if(!woliIdToWorkStepList.containsKey(step.WorkOrderLineItemId)) {
                List<WorkStep> stepList = new List<WorkStep>();
                stepList.add(step);
                woliIdToWorkStepList.put(step.WorkOrderLineItemId,stepList);
            }
            else { 
                List<WorkStep> stepList = woliIdToWorkStepList.get(step.WorkOrderLineItemId);
                stepList.add(step);
            	woliIdToWorkStepList.put(step.WorkOrderLineItemId,stepList);
            } 
            System.debug('woliIdToWorkStepList : '+woliIdToWorkStepList);
        }

        return woliIdToWorkStepList;
    }

    /**
	* Author : Sahil Wadhwa
	* Date : 08/06/2022
	* Description : Create the payload for planned work order complete
	**/
    private static string createCompletedChildWorkOrderPlayload(List<WorkStep> costList, WorkOrderLineItem woli) {
        String payload = '{';
        payload += '"TransactionID": "eventId",'
                + '"ContractorReference": "' + woli.MSN_Work_Line_Number__c + '",'
                + '"WorkOrderNo": "' + woli.MSN_Root_Work_Order__r.Work_Order_No__c + '",'
                + '"ContractorCode": "MSN",'
                + '"Asset":{'
                + '"AssetKey":' + woli.Asset.Comp_Key__c
                + '},'
                + '"ActivityCode": "' + woli.WorkType.MSN_ActivityCode__c + '",'
                + '"AssetCondition":"2",'
                + '"Comments": "' + woli.Description + '",'
                + '"Crew": "MSN",'
                + '"InitiatedDate":"' + woli.CreatedDate.format('yyyy-MM-dd\'T\'HH:mm:ss.sss',Userinfo.getTimeZone().toString()) + '",'
                + '"StartDate": "' + woli.MSN_Root_Work_Order__r.StartDate.format('yyyy-MM-dd\'T\'HH:mm:ss.sss',Userinfo.getTimeZone().toString())+ '",'
                + '"CompletedDate": "' + woli.MSN_Root_Work_Order__r.EndDate.format('yyyy-MM-dd\'T\'HH:mm:ss.sss',Userinfo.getTimeZone().toString())+ '",'
                + '"CompletedBy": "MSN",'
                + '"ResultCode": "COMP",'
                + '"VariationNo":"",'
                + '"TransactionType":"FM",';
        
        payload += '"Observations": [';
        if(costList != null){    
            for(WorkStep cost:costList) {
                String value = String.isNotBlank(cost.MSN_WorkStep_Answer__c) ? cost.MSN_WorkStep_Answer__c.replaceAll('\n', ' ') : '';
                payload += '{'
                        + '"Code": "' + cost.MSN_SPOT_Code__c + '",'
                        + '"Value": "' + value + '",'
                        + '"Date": "' + cost.LastModifiedDate.format('yyyy-MM-dd\'T\'HH:mm:ss.sss',Userinfo.getTimeZone().toString()) + '",'
                        + '"Detail": "' + cost.Description + '"'
                        + '},';
            }

        }
        else {
            payload += '{"Code": ""}';
        }
        payload = payload.removeEnd(',');
        payload += '],';

        payload += '"Failures":[{'
                + '"Code":"string",'
                + '"Detail":"string"'
                + '}]}';

        System.debug('@payload: ' + payload);

        return payload;
    }

    public static void createWoliFromWorkOrder(WorkOrder wo) {
        WorkOrderLineItem woli = new WorkOrderLineItem();
        woli.WorkOrderId = wo.Id;
        woli.WorkTypeId = wo.WorkType.Id;
        woli.AssetId = wo.Asset.Id;
        woli.Subject = wo.Subject;
        woli.Description = wo.Description;   

        System.debug('**WOLICreation: ' + woli);    
        Database.SaveResult woliSR = Database.insert(woli);
        Map<Id, List<Database.Error>> woliIdInsertErrors = new Map<id, List<Database.Error>>();

        if (!woliSR.isSuccess() ){
            woliIdInsertErrors.put( woliSR.getId(), woliSR.getErrors());
        }                        

        if ( woliIdInsertErrors.size() > 0 ){
            MSN_HandleErrorsException.insertSaveResultErrors('', 'Inserting Work Order Line Items', 'MSN_WorkOrderLineItemTriggerHelper', 
                'createWoliFromWorkOrder',MSN_Utility.getCurrentLineNumber(),woliIdInsertErrors);
        }
    }

    /**
	* Author : Bohao Chen
	* Date : 10/01/2023
	* Description : Call the work order line item cost integration
	**/
    public static void callWorkOrderCostIntegration (List<WorkOrderLineItem> completeWorkOrderLineItems) {
        System.debug('We are in work order cost integration');
        // Set<Id> workOrderIdSet = new Set<Id>();
        Map<Id,List<WorkStep>> woliIdToWorkStepList = new Map<Id,List<WorkStep>>();
        List<sObject> createEventList = new List<sObject>();                
        
        // Loop through wo order to form the Id set
        // for(WorkOrder wo:completeWorkOrderList) {
        //     workOrderIdSet.add(wo.Id);
        // }
        
        List<WorkStep> workStepList = [SELECT WorkOrderLineItemId, MSN_ScheduleItem_Code__c, 
                                            MSN_Service_Product_Code__c, MSN_WorkStep_Answer__c 
                                        FROM WorkStep 
                                        WHERE WorkOrderLineItemId IN :completeWorkOrderLineItems 
                                        AND MSN_Answer_Type__c = 'Schedule Item Code'];
        
        // Form the work order line item id to work step list
        for(WorkStep step : workStepList) {

            if(!woliIdToWorkStepList.containsKey(step.WorkOrderLineItemId)) {
                woliIdToWorkStepList.put(step.WorkOrderLineItemId, new List<WorkStep>());
            }

            woliIdToWorkStepList.get(step.WorkOrderLineItemId).add(step);
        }

        Integration_Endpoint__mdt endpointSetting = MSN_Utility.getEndpointSetting('Work_Order_Cost'); // TODO: what is the latest endpoint for work order line item cost?

        if(endpointSetting != null) {
            
            String endpointStr = endpointSetting.Endpoint__c;

            String method = 'PUT';
            
            for(WorkOrderLineItem woli : completeWorkOrderLineItems) {
                
                List<WorkStep> costList = woliIdToWorkStepList.get(woli.Id);

                // TODO: future improvement: 
                // Currenlty MSN_IntegrationUtility.generateOutboundIntegrationEvents can't handle any payload with a list inside
                // therefore, for any payload with lists, we cannot use MSN_IntegrationUtility.generateOutboundIntegrationEvents to
                // generate platform events
                String payload = MSN_IntegrationUtility.createCostPayload(costList, (SObject)woli); 

                //String endpoint = 'https://9fa04kq7a0.execute-api.ap-southeast-2.amazonaws.com/dev/v2/maintenance/workorder/'+wo.Work_Order_No__c+'/cost';
                String endpoint = endpointStr.replace('{workOrderNumber}', woli.MSN_EAM_Work_Order_No__c);
                Outbound_Integration__e platformEvent = new Outbound_Integration__e();
                platformEvent.EndPoint__c = endpoint;
                platformEvent.Method__c = method;
                platformEvent.Payload__c = payload;
                createEventList.add(platformEvent);
            }
            
            // Publishing the events
            try {
                Boolean eventCreation = MSN_GenericPlatformEventUtility.publishEvents(createEventList);
            } catch(Exception e){
                MSN_HandleErrorsException.insertLogException(e, '', '');
            }
        }
    }
}