force-app/main/default/objects/MSN_JobNotes__c/MSN_JobNotes__c.object-meta.xml
<CustomObject>
    <description>Used to capture Job Notes from the mobile field crew that need to be sent back into EAM.</description>
    <label>Job Note</label>
    <nameField>
        <displayFormat>JBN-{00000}</displayFormat>
        <label>Job Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MSN_JobNotes__c/fields/Concatenate_Job_Note__c.field-meta.xml
<CustomField>
    <fullName>Concatenate_Job_Note__c</fullName>
    <defaultValue>false</defaultValue>
    <description>determine if a job note will be concatenated on the work order</description>
    <label>Concatenate Job Note</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MSN_JobNotes__c/fields/Integrate_to_EAM__c.field-meta.xml
<CustomField>
    <fullName>Integrate_to_EAM__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if the job note will get sent to EAM</description>
    <label>Integrate to EAM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MSN_JobNotes__c/fields/MSN_JobNote_Details__c.field-meta.xml
<CustomField>
    <fullName>MSN_JobNote_Details__c</fullName>
    <description>Stores the actual Job Note eg entered by the field crew from the mobile app.</description>
    <label>Note Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MSN_JobNotes__c/fields/MSN_JobNote_Type__c.field-meta.xml
<CustomField>
    <fullName>MSN_JobNote_Type__c</fullName>
    <description>Determines the type of the Job Note eg a user entered &quot;Note&quot; or a system generated &quot;Field Update&quot;.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Note</fullName>
                <default>true</default>
                <label>Note</label>
            </value>
            <value>
                <fullName>Water On/Off</fullName>
            </value>
            <value>
                <fullName>Service Restore</fullName>
            </value>
            <value>
                <fullName>Dry Weather Overflow</fullName>
            </value>
            <value>
                <fullName>Impact Assessment for Water Off</fullName>
            </value>
            <value>
                <fullName>Service Request Update Type</fullName>
            </value>
            <value>
                <fullName>Field Update</fullName>
                <isActive>false</isActive>
                <label>Field Update</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MSN_JobNotes__c/fields/MSN_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>MSN_Work_Order__c</fullName>
    <description>Links a Job Note to its parent Work Order with a master-detail relationship. A Work Order is always required.</description>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Job Notes</relationshipLabel>
    <relationshipName>Job_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MSN_JobNotes__c/fields/Service_Request_Update_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Request_Update_Code__c</fullName>
    <label>Service Request Update Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Work_Order_No__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_No__c</fullName>
    <description>https://watercarestp.atlassian.net/browse/MSRS-93</description>
    <externalId>true</externalId>
    <label>EAM Work Order Number</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WorkOrder/recordTypes/MSN.recordType-meta.xml
<RecordType>
    <fullName>MSN</fullName>
    <active>true</active>
    <description>Please use this for all normal planned or reactive work (NOT reinstatement)</description>
    <label>MSN</label>
</RecordType>

force-app/main/default/classes/MSN_JobNotesTrigger_Test.cls
/**
* Author : Ashwini Patil
* Date : 18/08/2022
* Updated By: Bohao Chen
* Updated Date: 27/01/2023
* Description : Test class to cover MSN_JobNoteTriggerHandler and MSN_JobNoteTriggerHelper class
**/
@isTest
public class MSN_JobNotesTrigger_Test {

    @TestSetup
    static void testDataSetup() {

        OperatingHours oh = (OperatingHours)TestDataFactory.createSObject('OperatingHours', new Map<String,Object>{
            'Name' => 'test operation hours',
            'TimeZone' => 'Pacific/Auckland'
        });

        ServiceTerritory st = (ServiceTerritory)TestDataFactory.createSObject('ServiceTerritory', new Map<String,Object>{
            'IsActive' => true,
            'OperatingHoursId' => oh.Id
        });

        WorkType wt = (WorkType)TestDataFactory.createSObject('WorkType');

        // create a sample completed planned work order 
        Id msnWorkOrderRtId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('MSN').getRecordTypeId();
        
        WorkOrder wo = (WorkOrder)TestDataFactory.createSObject('WorkOrder', new Map<String,Object>{
            'ServiceTerritoryId' =>  st.Id,
            'WorkTypeId' => wt.Id,
            'Status' => 'New',
            'recordTypeId' => msnWorkOrderRtId,
            'Work_Order_No__c' => 'WO-000008',
            'Street' => '44 Meadowbank Road', 
            'PostalCode' => '1072', 
            'Country' => 'New Zealand', 
            'City' => 'Auckland', 
            'Priority' => '7'
        });
    }

    @isTest
    public static void insertTest() {   
        
        WorkOrder wo = [SELECT Id FROM WorkOrder LIMIT 1];
                      
        MSN_Integration.integrationQueued = false;
        Test.startTest();

        List<MSN_JobNotes__c> JON = new List<MSN_JobNotes__c>();
        for(Integer i=0;i<4;i++) {
            JON.add(new MSN_JobNotes__c(MSN_Work_Order__c = wo.Id, MSN_JobNote_Details__c = 'Test data for note details field', Concatenate_Job_Note__c =
                                        true, MSN_JobNote_Type__c = 'Service Request Update Type', Integrate_to_EAM__c = true, Service_Request_Update_Code__c = 'WATEROFF'));
            i++;
        }
        
        JON.add(new MSN_JobNotes__c(MSN_Work_Order__c = wo.Id, MSN_JobNote_Details__c = 'Test data for note details field', 
                                    Concatenate_Job_Note__c = true, MSN_JobNote_Type__c = 'Service Restore'));

        insert JON;

        Test.stopTest();
    }
    
    @isTest
    static void updateJobNotestest(){

        WorkOrder wo = [SELECT Id FROM WorkOrder LIMIT 1];

        List<MSN_JobNotes__c> jobNotes = new List<MSN_JobNotes__c>();
        for(Integer i=0;i<4;i++) {
            jobNotes.add(new MSN_JobNotes__c(MSN_Work_Order__c = wo.Id, MSN_JobNote_Details__c = 'Test data for note details field', Concatenate_Job_Note__c =
                                        true, MSN_JobNote_Type__c = 'Service Request Update Type', Integrate_to_EAM__c = true, Service_Request_Update_Code__c = 'WATEROFF'));
            i++;
        }
        
        jobNotes.add(new MSN_JobNotes__c(MSN_Work_Order__c = wo.Id, MSN_JobNote_Details__c = 'Test data for note details field', 
                                    Concatenate_Job_Note__c = true, MSN_JobNote_Type__c = 'Service Restore'));

        insert jobNotes;
        
        Test.startTest();
        for(MSN_JobNotes__c jn : jobNotes) {
            jn.MSN_JobNote_Details__c = 'updated note details';
        }

        Test.stopTest();
        update jobNotes;
    }       

    @isTest
    static void deleteJobNotestest(){

        WorkOrder wo = [SELECT Id FROM WorkOrder LIMIT 1];
        
        List<MSN_JobNotes__c> jobNotes = new List<MSN_JobNotes__c>();
        for(Integer i=0;i<4;i++) {
            jobNotes.add(new MSN_JobNotes__c(MSN_Work_Order__c = wo.Id, MSN_JobNote_Details__c = 'Test data for note details field', Concatenate_Job_Note__c =
                                        true, MSN_JobNote_Type__c = 'Service Request Update Type', Integrate_to_EAM__c = true, Service_Request_Update_Code__c = 'WATEROFF'));
            i++;
        }
        
        jobNotes.add(new MSN_JobNotes__c(MSN_Work_Order__c = wo.Id, MSN_JobNote_Details__c = 'Test data for note details field', 
                                    Concatenate_Job_Note__c = true, MSN_JobNote_Type__c = 'Service Restore'));

        insert jobNotes;
        
        Test.startTest();
        delete jobNotes;
        Test.stopTest();
    }
}