force-app/main/default/objects/Job_Notes_Type_Mapping__mdt/Job_Notes_Type_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Create Job Note for Service Request Updates</description>
    <label>Job Notes Type Mapping</label>
    <pluralLabel>Job Notes Type Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Job_Notes_Type_Mapping__mdt/fields/Concatenate_Job_Note__c.field-meta.xml
<CustomField>
    <fullName>Concatenate_Job_Note__c</fullName>
    <defaultValue>true</defaultValue>
    <description>determine if a job note will be concatenated on the work order</description>
    <label>Concatenate Job Note</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Notes_Type_Mapping__mdt/fields/Integrate_to_EAM__c.field-meta.xml
<CustomField>
    <fullName>Integrate_to_EAM__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Determines if the job note will get sent to EAM</description>
    <label>Integrate to EAM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Notes_Type_Mapping__mdt/fields/Is_Not_Blank__c.field-meta.xml
<CustomField>
    <fullName>Is_Not_Blank__c</fullName>
    <defaultValue>true</defaultValue>
    <description>indicate the value of the target field should not be blank</description>
    <label>Not Blank</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Notes_Type_Mapping__mdt/fields/Payload_Fields__c.field-meta.xml
<CustomField>
    <fullName>Payload_Fields__c</fullName>
    <description>which fields are going to be included in the payload (to be updated in the future)</description>
    <label>Payload Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Notes_Type_Mapping__mdt/fields/Service_Request_Update_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Request_Update_Code__c</fullName>
    <label>Service Request Update Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Notes_Type_Mapping__mdt/fields/Trigger_Field__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Field__c</fullName>
    <description>which field on the object triggers job note creation</description>
    <label>Trigger Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Notes_Type_Mapping__mdt/fields/Trigger_Object__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Object__c</fullName>
    <description>which object triggers job note creation</description>
    <inlineHelpText>which object triggers job note creation</inlineHelpText>
    <label>Trigger Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Notes_Type_Mapping__mdt/fields/Trigger_Value__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Value__c</fullName>
    <description>which field value triggers job note creation</description>
    <label>Trigger Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Notes_Type_Mapping__mdt/fields/Work_Order_Id_Field__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Id_Field__c</fullName>
    <description>field API name indicates the work order id on the object.</description>
    <label>Work Order Id Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MSN_JobNotes__c/MSN_JobNotes__c.object-meta.xml
<CustomObject>
    <description>Used to capture Job Notes from the mobile field crew that need to be sent back into EAM.</description>
    <label>Job Note</label>
    <nameField>
        <displayFormat>JBN-{00000}</displayFormat>
        <label>Job Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MSN_JobNotes__c/fields/Concatenate_Job_Note__c.field-meta.xml
<CustomField>
    <fullName>Concatenate_Job_Note__c</fullName>
    <defaultValue>false</defaultValue>
    <description>determine if a job note will be concatenated on the work order</description>
    <label>Concatenate Job Note</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MSN_JobNotes__c/fields/Integrate_to_EAM__c.field-meta.xml
<CustomField>
    <fullName>Integrate_to_EAM__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if the job note will get sent to EAM</description>
    <label>Integrate to EAM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MSN_JobNotes__c/fields/MSN_JobNote_Details__c.field-meta.xml
<CustomField>
    <fullName>MSN_JobNote_Details__c</fullName>
    <description>Stores the actual Job Note eg entered by the field crew from the mobile app.</description>
    <label>Note Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MSN_JobNotes__c/fields/MSN_JobNote_Type__c.field-meta.xml
<CustomField>
    <fullName>MSN_JobNote_Type__c</fullName>
    <description>Determines the type of the Job Note eg a user entered &quot;Note&quot; or a system generated &quot;Field Update&quot;.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Note</fullName>
                <default>true</default>
                <label>Note</label>
            </value>
            <value>
                <fullName>Water On/Off</fullName>
            </value>
            <value>
                <fullName>Service Restore</fullName>
            </value>
            <value>
                <fullName>Dry Weather Overflow</fullName>
            </value>
            <value>
                <fullName>Impact Assessment for Water Off</fullName>
            </value>
            <value>
                <fullName>Service Request Update Type</fullName>
            </value>
            <value>
                <fullName>Field Update</fullName>
                <isActive>false</isActive>
                <label>Field Update</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MSN_JobNotes__c/fields/MSN_Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>MSN_Service_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a Service Appointment this Job note might be related to in addition to its parent Work Order.</description>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Job Notes</relationshipLabel>
    <relationshipName>Job_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MSN_JobNotes__c/fields/MSN_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>MSN_Work_Order__c</fullName>
    <description>Links a Job Note to its parent Work Order with a master-detail relationship. A Work Order is always required.</description>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Job Notes</relationshipLabel>
    <relationshipName>Job_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MSN_JobNotes__c/fields/Service_Request_Update_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Request_Update_Code__c</fullName>
    <label>Service Request Update Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MSN_JobNotes__c/fields/Work_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup used to (optionally) relate the Job Note to a Work Order Line Item in addition to its parent Work Order.</description>
    <label>Work Order Line Item</label>
    <referenceTo>WorkOrderLineItem</referenceTo>
    <relationshipLabel>Job Notes</relationshipLabel>
    <relationshipName>Job_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Work_Order_No__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_No__c</fullName>
    <description>https://watercarestp.atlassian.net/browse/MSRS-93</description>
    <externalId>true</externalId>
    <label>EAM Work Order Number</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WorkStep/fields/MSN_Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>MSN_Service_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This lookup relationship is used to link a &quot;Work Step&quot; to a specific Service Appointment during the work step has been completed/answered. This is particularly important to link a &quot;Schedule Item Code&quot; work step to a Service Appointment, in order to identify what type of work a specific crew/subcontractor has done during their Service Appointment. Otherwise, the Work Steps are only linked to a Work Order or Work Order Line Item, making it impossible to tell on which Service Appointment the Work Step has been completed.</description>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Work Steps</relationshipLabel>
    <relationshipName>Work_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkStep/fields/MSN_WorkStep_Answer__c.field-meta.xml
<CustomField>
    <fullName>MSN_WorkStep_Answer__c</fullName>
    <description>Used to record the Answer that has been given to a Work Step question via the Flow &quot;MSN - Field Service Mobile App - Work Step Answers&quot; as part of a Work Plan for a given Work Order.</description>
    <label>Work Step Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/MSN_JobNoteUtility.cls
/**
 * @File Name          : MSN_JobNoteUtility.cls
 * @Description        : Utility class for Job Note 
 * @Author             : Bohao Chen
 * @Group              : 
 * @Last Modified By   : Bohao Chen
 * @Last Modified On   : 31/08/2022
 * @Modification Log   : 
 * Ver      Date            Author                  Modification
 * 1.0      31/08/2022      Bohao Chen              Initial Version
**/
public with sharing class MSN_JobNoteUtility {
    
    // this method is to create a job note when records gets updated based on the Custom Metadata Type "Job Notes Type Mappings"
    public static void createJobNotes(Map<Id, sObject> newRecords, Map<Id, sObject> oldRecords) {
        List<MSN_JobNotes__c> jobNotes = new List<MSN_JobNotes__c>();

        for(Id recId : newRecords.keySet()) {
            sObject newRec = newRecords.get(recId);
            String objectApiName = newRec.getSObjectType().getDescribe().getName();
            System.debug('@objectApiName: ' + objectApiName);

            Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get(objectApiName).getDescribe().fields.getMap();

            // get custom metadata type Job_Notes_Type_Mapping__mdt
            for ( Job_Notes_Type_Mapping__mdt jobNoteTypeMapping : Job_Notes_Type_Mapping__mdt.getAll().values()){
                
                if(jobNoteTypeMapping.Trigger_Object__c.equalsIgnoreCase(objectApiName)) {

                    String triggerField = jobNoteTypeMapping.Trigger_Field__c;
                                        
                    // when trigger field value changed
                    if(newRec.get(triggerField) != null && (oldRecords == null || oldRecords.get(recId).get(triggerField) != newRec.get(triggerField))) {

                        String value = String.valueOf(newRec.get(triggerField));
                        String triggerValue = jobNoteTypeMapping.Trigger_Value__c;

                        System.debug('@trigger field string value: ' + value);

                        if((objectApiName.equalsIgnoreCase('WorkStep') && triggerField.equalsIgnoreCase('MSN_WorkStep_Answer__c') && value.contains(triggerValue))
                            || (String.isNotBlank(triggerValue) && value.equalsIgnoreCase(triggerValue))
                            || (String.isBlank(triggerValue) && String.isNotBlank(value) == jobNoteTypeMapping.Is_Not_Blank__c)) {

                            System.debug('@same value');
                            // create job note
                            jobNotes.add(createJobNote(newRec, jobNoteTypeMapping, objectApiName, fieldMap));
                        }
                    }
                }
            }                       
        }

        if(!jobNotes.isEmpty()) {
            insert jobNotes;
        }
    }

    private static MSN_JobNotes__c createJobNote(sObject record, Job_Notes_Type_Mapping__mdt jobNoteTypeMapping, String objectApiName, Map<String, Schema.SObjectField> fieldMap) {
        
        Id workOrderId = (Id)record.get(jobNoteTypeMapping.Work_Order_Id_Field__c);
        Id serviceAppointmentId;
        Id workOrderLineItemId;

        if(objectApiName == 'ServiceAppointment') {
            serviceAppointmentId = record.Id;
        }
        else if(objectApiName == 'WorkOrderLineItem') {
            workOrderLineItemId = record.Id;
        }

        MSN_JobNotes__c jobNote = new MSN_JobNotes__c(
            MSN_Work_Order__c = workOrderId,
            MSN_Service_Appointment__c = serviceAppointmentId,
            Work_Order_Line_Item__c = workOrderLineItemId,
            MSN_JobNote_Type__c = 'Service Request Update Type',
            Concatenate_Job_Note__c = jobNoteTypeMapping.Concatenate_Job_Note__c,
            Integrate_to_EAM__c = jobNoteTypeMapping.Integrate_to_EAM__c,
            Service_Request_Update_Code__c = jobNoteTypeMapping.Service_Request_Update_Code__c,
            MSN_JobNote_Details__c = populateJobNoteDetails(record, jobNoteTypeMapping.Payload_Fields__c, fieldMap)
        );

        return jobNote;
    }

    public static String populateJobNoteDetails(sObject record, String fieldsStr, Map<String, Schema.SObjectField> fieldMap) {
        String details = '';
        if(String.isNotBlank(fieldsStr)) {
            if(fieldsStr.contains(',')) {
                for(String fieldStr : fieldsStr.split(',')) {
                    details += String.format('{0}\n', new String[]{fieldMap.get(fieldStr).getDescribe().getLabel() + ':' + convertValueToStr(record, fieldStr, fieldMap)});
                }
                details = details.removeEnd('\n');
            }
            else {
                details += fieldMap.get(fieldsStr).getDescribe().getLabel() + ':' + convertValueToStr(record, fieldsStr, fieldMap);
            }
            
            System.debug('@details: ' + details);
        }

        return details;
    }

    // this method is to create a job note when receiving work order update from EAM
    public static MSN_JobNotes__c createJobNote(String jsonString) {
		MSN_UpdateReactiveMaintenanceWrapper jobNoteWrapper = (MSN_UpdateReactiveMaintenanceWrapper)System.JSON.deserialize(jsonString, MSN_UpdateReactiveMaintenanceWrapper.class);

        // search for the work order based on EAM work order number (Work_Order_No__c)
        String eamWorkOrderNum = jobNoteWrapper.WorkOrderNo;

        List<WorkOrder> workOrders = [SELECT Id FROM WorkOrder Where Work_Order_No__c =: eamWorkOrderNum];

        MSN_JobNotes__c jobNote;
        if(workOrders.isEmpty()) {
            throw new MSN_Utility.CustomException('Couldn\'t find the work order \'' + eamWorkOrderNum + '\'');
        }
        else {
            jobNote = new MSN_JobNotes__c();
            jobNote.Service_Request_Update_Code__c = jobNoteWrapper.UpdateType;
            jobNote.MSN_JobNote_Details__c = jobNoteWrapper.Comments;
            jobNote.MSN_Work_Order__c = workOrders[0].Id;
            jobNote.MSN_JobNote_Type__c = 'Service Request Update Type';
            insert jobNote;
        }
        
        return jobNote;
    }

    @TestVisible private static String convertValueToStr(sObject record, String fieldStr, Map<String, Schema.SObjectField> fieldMap) {
        
        String val;

        if(fieldMap.get(fieldStr).getDescribe().getType() == Schema.DisplayType.DATETIME) {
            System.debug('@this is a datetime field');

            Datetime dt = Datetime.valueOf(record.get(fieldStr));
            val = dt.format('yyyy-MM-dd h:mm a');
            System.debug('@myDate: ' + val);
        }
        else {
            val = String.valueOf(record.get(fieldStr));
        }

        return val;
    }
}