force-app/main/default/objects/ServiceAppointment/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>P1</fullName>
            </value>
            <value>
                <fullName>P2</fullName>
            </value>
            <value>
                <fullName>P3</fullName>
            </value>
            <value>
                <fullName>P4</fullName>
            </value>
            <value>
                <fullName>P5</fullName>
            </value>
            <value>
                <fullName>P6</fullName>
            </value>
            <value>
                <fullName>P7</fullName>
            </value>
            <value>
                <fullName>P8</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Contractor_Area__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Area__c</fullName>
    <label>Contractor Area</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Transaction_ID__c</fullName>
    <description>Source is ION</description>
    <label>Transaction ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Work_Order_No__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_No__c</fullName>
    <description>https://watercarestp.atlassian.net/browse/MSRS-93</description>
    <externalId>true</externalId>
    <label>EAM Work Order Number</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WorkOrder/recordTypes/MSN.recordType-meta.xml
<RecordType>
    <fullName>MSN</fullName>
    <active>true</active>
    <description>Please use this for all normal planned or reactive work (NOT reinstatement)</description>
    <label>MSN</label>
</RecordType>

force-app/main/default/classes/MSN_WorkOrderTrigger_Test.cls
/**
	* Author : Ashwini Patil
	* Date : 15/08/2022
	* Description : Test class to cover work order trigger, work order helper class and handler class
	**/

@isTest 
public class MSN_WorkOrderTrigger_Test {
    
	@isTest
    public static void insertmethod() {   
        //Create asset record
    	Asset asset = new Asset(Name = 'Water Meter-458800-A06A138755 18-26 Wellesley ST-E Auckland Central');
    	insert asset;
    
        //Create ServiceTerritory record
    	ServiceTerritory st = (ServiceTerritory)TestDataFactory.createSObject('ServiceTerritory', new Map<String,Object>{
            'IsActive' => true
        });
        
        Id msnWorkOrderRtId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('MSN').getRecordTypeId();

        //Create WorkType record
    	WorkType wt = new WorkType(Name = 'Watermeter - Planned Replacement', DurationType = 'Minutes', EstimatedDuration = 40 );
        insert wt;
    
        //Create WorkOrder record
    	WorkOrder wo = new WorkOrder(Transaction_ID__c = '0800052712', Work_Order_No__c = '20035223', ServiceTerritoryId = st.Id, 
                                     WorkTypeId = wt.Id, Contractor_Area__c = 'METRO', Subject = 'Replace the water meters as instructed',
                                     AssetId = asset.Id, Street = '44 Meadowbank Road', PostalCode = '1072', Country = 'New Zealand', City = 'Auckland',
                                     Priority = '7', RecordTypeId = msnWorkOrderRtId);
        insert wo;
        
        
        //Create ServiceAppointment record
        ServiceAppointment sa = new ServiceAppointment(ParentRecordId = wo.Id, Status = 'New', Street = wo.Street, PostalCode = wo.PostalCode, 
                                                       Country = wo.Country, City = wo.City, Priority__c = wo.Priority,
                                                       ServiceTerritoryId = wo.ServiceTerritoryId);
        insert sa;
        
		 
        //Create WorkOrderLineItem record
        WorkOrderLineItem woli = new WorkOrderLineItem(WorkOrderId = wo.Id, Status = 'New', Street = wo.Street, PostalCode = wo.PostalCode, 
                                                       Country = wo.Country, City = wo.City, WorkTypeId = wt.Id, AssetId = asset.Id, 
                                                       Subject = 'PLANNED METER REPLACEMENT', Description = 'MSN EAM SFS WMTPMR Test' );
        
    }  
    
}